version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.8.1-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pass4Dev1!"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  eventstore:
    image: eventstore/eventstore
    environment:
      EVENTSTORE_RUN_PROJECTIONS: "System"
      EVENTSTORE_START_STANDARD_PROJECTIONS: "True"
    ports:
      - 2113:2113
      - 1113:1113