//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cegeka.Guild.Pokeverse.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cegeka.Guild.Pokeverse.Common.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The battle does not exist!.
        /// </summary>
        public static string BattleDoesNotExist {
            get {
                return ResourceManager.GetString("BattleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle has already ended!.
        /// </summary>
        public static string BattleHasEnded {
            get {
                return ResourceManager.GetString("BattleHasEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle is still ongoing!.
        /// </summary>
        public static string BattleIsOngoing {
            get {
                return ResourceManager.GetString("BattleIsOngoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pokemon cannot fight itself!.
        /// </summary>
        public static string CannotFightItself {
            get {
                return ResourceManager.GetString("CannotFightItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use this ability yet!.
        /// </summary>
        public static string CannotUseAbility {
            get {
                return ResourceManager.GetString("CannotUseAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemon is invalid!.
        /// </summary>
        public static string InvalidPokemon {
            get {
                return ResourceManager.GetString("InvalidPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pokemon definition is invalid!.
        /// </summary>
        public static string InvalidPokemonDefinition {
            get {
                return ResourceManager.GetString("InvalidPokemonDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trainer is invalid!.
        /// </summary>
        public static string InvalidTrainer {
            get {
                return ResourceManager.GetString("InvalidTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trainer name is invalid!.
        /// </summary>
        public static string InvalidTrainerName {
            get {
                return ResourceManager.GetString("InvalidTrainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not the active player, wait for your turn!.
        /// </summary>
        public static string NotYourTurn {
            get {
                return ResourceManager.GetString("NotYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemon is already in battle!.
        /// </summary>
        public static string PokemonAlreadyInBattle {
            get {
                return ResourceManager.GetString("PokemonAlreadyInBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given pokemon does not exist!.
        /// </summary>
        public static string PokemonDoesNotExist {
            get {
                return ResourceManager.GetString("PokemonDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two pokemons of the same trainer cannot fight!.
        /// </summary>
        public static string SiblingsCannotFight {
            get {
                return ResourceManager.GetString("SiblingsCannotFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ability!.
        /// </summary>
        public static string UnknownAbility {
            get {
                return ResourceManager.GetString("UnknownAbility", resourceCulture);
            }
        }
    }
}
